apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  database-url: <veritabanı-bağlantı-url>
  service-a-url: <service-a-adresi>
  service-b-url: <service-b-adresi>
  ...

apiVersion: v1
kind: ConfigMap
metadata:
  name: documentdb-config
data:
  connection-uri: mongodb://<username>:<password>@<host>:<port>/<database-name>
