apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  database-url: <veritabanı-bağlantı-url>
  service-a-url: <service-a-adresi>
  service-b-url: <service-b-adresi>
  ...

apiVersion: v1
kind: ConfigMap
metadata:
  name: documentdb-config
data:
  connection-uri: mongodb://<username>:<password>@<host>:<port>/<database-name>



apiVersion: v1
kind: Pod
metadata:
  name: documentdb-pod
spec:
  containers:
    - name: app-container
      image: your-app-image
      env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: documentdb-config
              key: connection-uri


aws eks create-cluster --name my-cluster --role-arn <eks-service-role-arn> --resources-vpc-config subnetIds=<subnet-ids>,securityGroupIds=<security-group-id>
